"""Process the genotype data from the TF-Gene-SNP file generated by Zhifu."""
# biopipen v0.32.3
from pipen import Pipen
from pipen_args import parser
from biopipen.ns.misc import Shell
from biopipen.ns.snp import (
    PlinkFromVcf as PlinkFromVcf_,
    PlinkFilter as PlinkFilter_,
    Plink2GTMat as Plink2GTMat_,
)

parser.add_argument("--vcf", help="VCF file", required=True)
parser.add_argument("--snpfile", help="SNP file", required=True)
args = parser.parse_extra_args()


class PlinkFromVcf(PlinkFromVcf_):
    input_data = [args.vcf]
    envs = {
        "chr": "1-22",
        "set_missing_var_ids": None,
    }


class PlinkFilter(PlinkFilter_):
    requires = PlinkFromVcf
    input_data = lambda ch1: [(ch1.iloc[0, 0], None, args.snpfile)]
    envs = {"keep": True}


class Plink2GTMat(Plink2GTMat_):
    requires = PlinkFilter
    envs = {
        "samid": "{iid}",
        "varid": "{varid}",
    }

class VariantCoords(Shell):
    requires = PlinkFilter
    output = "outfile:file:variant_coords.bed"
    envs = {
        "cmd": (
            """awk '{print "chr"$1"\\t"$4-1"\\t"$4"\\t"$2"\\t0\\t+\\t"$6"\\t"$5}' """
            """$infile/*.bim > $outfile"""
        )
    }

class ProcessGT(Pipen):
    starts = PlinkFromVcf  # type: ignore


if __name__ == "__main__":
    ProcessGT().run()
